name: CD Pipeline

on:
  pull_request:
  types: [closed]
  branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update Server Repo
        uses: maddox/actions/ssh/@master
        env:
          PRIVATE_KEY: ${{ secrets.KEY_PORTFOLIO }}
          HOST: ${{ secrets.USER_PORTFOLIO }}
          USER: ${{ secrets.USER_PORTFOLIO }}
        with:
          args: |
            cd repo
            git pull
